import type { DrugEntry } from './types';
import { contentReview } from './sources';

export const drugs: DrugEntry[] = [
  { ...contentReview, id: 'noradrenalina', name: 'Noradrenalina', aliases: ['norepinefrina', 'NA', 'norepi'], category: 'Vasoactivos', summary: 'Vasopresor para sostén de presión y perfusión.',
    doses: [], precautions: 'Corregir hipovolemia cuando corresponda. Riesgo de isquemia y necrosis por extravasación. Confirmar si el envase expresa base o sal.', monitoring: 'Presión arterial, perfusión, ritmo y sitio de infusión.', infusionUnit: 'µg/kg/min', sourceIds: ['noradrenalina'] },
  { ...contentReview, id: 'adrenalina', name: 'Adrenalina', aliases: ['epinefrina', 'epi'], category: 'Vasoactivos', summary: 'El bolo de reanimación y la infusión con pulso son esquemas distintos.',
    doses: [{ context: 'Paro cardíaco adulto', text: '1 mg IV/IO cada 3–5 min, según secuencia ACLS.', sourceId: 'arrest' }, { context: 'Bradicardia con pulso, infusión', text: '2–10 µg/min IV, titulados a respuesta.', sourceId: 'brady' }],
    precautions: 'No trasladar el bolo del paro a un paciente con pulso.', monitoring: 'Ritmo, presión y perfusión.', infusionUnit: 'µg/min', sourceIds: ['arrest', 'brady'] },
  { ...contentReview, id: 'dobutamina', name: 'Dobutamina', aliases: ['dobuta'], category: 'Inotrópicos', summary: 'Soporte inotrópico de corta duración en contractilidad deprimida.',
    doses: [], precautions: 'Corregir hipovolemia si existe. Puede aumentar frecuencia, ectopia e isquemia.', monitoring: 'ECG, presión, diuresis y respuesta hemodinámica.', infusionUnit: 'µg/kg/min', sourceIds: ['dobutamina'] },
  { ...contentReview, id: 'milrinona', name: 'Milrinona', aliases: ['inodilatador', 'PDE3'], category: 'Inotrópicos', summary: 'Inodilatador con eliminación renal relevante.',
    doses: [], precautions: 'La insuficiencia renal prolonga su eliminación. Revisar ajuste de infusión; riesgo de hipotensión y arritmias.', monitoring: 'Función renal, presión, ECG y electrolitos.', infusionUnit: 'µg/kg/min', sourceIds: ['milrinona'] },
  { ...contentReview, id: 'dopamina', name: 'Dopamina', aliases: ['dopa'], category: 'Vasoactivos', summary: 'Alternativa de infusión cronotrópica en bradicardia sintomática.',
    doses: [{ context: 'Bradicardia con pulso', text: '5–20 µg/kg/min IV, titular a respuesta.', sourceId: 'brady' }],
    precautions: 'Si no responde, preparar estimulación. Este esquema no define tratamiento para todos los tipos de shock.', monitoring: 'Ritmo y perfusión.', infusionUnit: 'µg/kg/min', sourceIds: ['brady'] },
  { ...contentReview, id: 'vasopresina', name: 'Vasopresina', aliases: ['AVP', 'vasoplejia'], category: 'Vasoactivos', summary: 'Vasopresor para shock vasodilatador, según contexto.',
    doses: [{ context: 'Inicio en shock séptico según ficha estadounidense', text: '0,01 U/min IV.', sourceId: 'vasopresina' }, { context: 'Inicio en shock poscardiotomía según ficha estadounidense', text: '0,03 U/min IV. La titulación depende de respuesta y protocolo.', sourceId: 'vasopresina' }],
    precautions: 'No existe una dosis fija universal. Las unidades U no son intercambiables con mg. Riesgo de isquemia y reducción del gasto.', monitoring: 'Presión, perfusión, sodio y función cardíaca.', infusionUnit: 'U/min', sourceIds: ['vasopresina'] },
  { ...contentReview, id: 'levosimendan', name: 'Levosimendán', aliases: ['simdax', 'sensibilizador calcio'], category: 'Inotrópicos', summary: 'Soporte en descompensación severa de IC seleccionada.',
    doses: [], precautions: 'Contraindicado con ClCr <30 mL/min, hipotensión grave, hepatopatía grave o antecedente de torsades según AEMPS. No extrapolar a todo shock.', monitoring: 'Presión, ECG, K y función renal; los metabolitos prolongan el efecto.', infusionUnit: 'µg/kg/min', sourceIds: ['levosimendan'] },
  { ...contentReview, id: 'nitroglicerina', name: 'Nitroglicerina', aliases: ['NTG', 'trinitrina', 'nitratos'], category: 'Vasodilatadores', summary: 'Vasodilatación en situaciones isquémicas y congestivas seleccionadas.',
    doses: [], precautions: 'Evitar con inhibidores PDE5, hipotensión o taponamiento. Revisar dependencia de precarga y equipo de administración.', monitoring: 'Presión y síntomas durante la titulación.', infusionUnit: 'µg/min', sourceIds: ['nitroglicerina'] },
  { ...contentReview, id: 'atropina', name: 'Atropina', aliases: ['bradicardia'], category: 'Arritmias', summary: 'Bradicardia con compromiso hemodinámico.',
    doses: [{ context: 'Adulto, bradicardia con pulso', text: '1 mg IV; repetir cada 3–5 min. Máximo total: 3 mg.', sourceId: 'brady' }],
    precautions: 'No retrasar estimulación si el bloqueo avanzado es inestable o no responde.', monitoring: 'ECG y perfusión.', sourceIds: ['brady'] },
  { ...contentReview, id: 'adenosina', name: 'Adenosina', aliases: ['TSV', 'TPSV'], category: 'Arritmias', summary: 'Taquicardia regular, tras evaluar estabilidad y QRS.',
    doses: [{ context: 'Adulto, TSV regular', text: '6 mg IV rápido, seguido de lavado con solución salina; 12 mg si precisa.', sourceId: 'tachy' }],
    precautions: 'No usar en taquicardia irregular/polimórfica. Revisar broncoespasmo, bloqueos y situaciones que requieran reducir dosis.', monitoring: 'ECG continuo y equipo de reanimación disponible.', sourceIds: ['tachy', 'als'] },
  { ...contentReview, id: 'amiodarona', name: 'Amiodarona', aliases: ['amio', 'cordarone'], category: 'Arritmias', summary: 'Esquemas diferentes según pulso y arritmia.',
    doses: [{ context: 'FV/TV sin pulso refractaria', text: '300 mg IV/IO; segunda dosis de 150 mg según ACLS.', sourceId: 'arrest' }, { context: 'TV estable con pulso', text: '150 mg IV en 10 min; después 1 mg/min durante las primeras 6 h.', sourceId: 'tachy' }],
    precautions: 'Evitar en FA preexcitada. Revisar QT, hipotensión y bradicardia.', monitoring: 'ECG, presión y electrolitos.', infusionUnit: 'mg/min', renalRuleIds: ['amiodarona'], sourceIds: ['arrest', 'tachy', 'als'] },
  { ...contentReview, id: 'lidocaina', name: 'Lidocaína', aliases: ['lignocaina'], category: 'Arritmias', summary: 'Alternativa antiarrítmica en FV/TV sin pulso refractaria.',
    doses: [{ context: 'Paro adulto, FV/TV sin pulso', text: '1–1,5 mg/kg IV/IO; segunda dosis 0,5–0,75 mg/kg según ACLS.', sourceId: 'arrest' }],
    precautions: 'Confirmar peso y dosis ya administradas; el esquema de paro no define la infusión posterior.', monitoring: 'ECG y respuesta durante reanimación.', infusionUnit: 'mg/min', sourceIds: ['arrest'] },
  { ...contentReview, id: 'metoprolol', name: 'Metoprolol', aliases: ['betabloqueante', 'beta bloqueante'], category: 'Control de frecuencia', summary: 'Control de frecuencia en FA sin preexcitación, según estabilidad.',
    doses: [], precautions: 'Evitar IV en disfunción sistólica con IC descompensada; valorar presión, conducción y broncoespasmo.', monitoring: 'FC, ECG y presión.', sourceIds: ['als', 'af'] },
  { ...contentReview, id: 'esmolol', name: 'Esmolol', aliases: ['betabloqueante corto', 'beta bloqueante'], category: 'Control de frecuencia', summary: 'Betabloqueo IV titulable; contexto arrítmico o aórtico.',
    doses: [], precautions: 'Revisar perfusión, IC descompensada y trastornos de conducción.', monitoring: 'ECG y presión durante la infusión.', infusionUnit: 'µg/kg/min', sourceIds: ['als', 'aorta'] },
  { ...contentReview, id: 'diltiazem', name: 'Diltiazem', aliases: ['bloqueante calcico', 'FA'], category: 'Control de frecuencia', summary: 'Control de frecuencia en FA seleccionada.',
    doses: [], precautions: 'Requiere FEVI >40% para esta estrategia. Evitar en FA preexcitada y disfunción sistólica descompensada.', monitoring: 'Presión, FC y conducción AV.', infusionUnit: 'mg/h', sourceIds: ['af', 'als'] },
  { ...contentReview, id: 'digoxina', name: 'Digoxina', aliases: ['digital', 'digitalicos'], category: 'Control de frecuencia', summary: 'Opción de control de frecuencia que requiere individualización.',
    doses: [], precautions: 'Revisar función renal, K, interacciones y exposición previa. No usar en FA preexcitada.', monitoring: 'ECG, función renal, electrolitos y niveles cuando corresponda.', renalRuleIds: ['digoxina'], sourceIds: ['af', 'als'] },
  { ...contentReview, id: 'furosemida', name: 'Furosemida', aliases: ['diuretico de asa', 'lasix'], category: 'Congestión', summary: 'Diurético de asa; ajustar a congestión y respuesta.',
    doses: [{ context: 'Edema, dosis inicial de ficha técnica en adultos', text: '20–40 mg IV lentamente (1–2 min). La exposición previa y la respuesta modifican el esquema.', sourceId: 'furosemida' }],
    precautions: 'Vigilar depleción de volumen, electrolitos y ototoxicidad. La dosis inicial no es un techo ni sirve para todos los pacientes.', monitoring: 'Diuresis, balance, presión, creatinina, Na, K y Mg.', infusionUnit: 'mg/h', sourceIds: ['furosemida'] },
  { ...contentReview, id: 'heparina', name: 'Heparina no fraccionada', aliases: ['HNF', 'UFH', 'heparina sodica'], category: 'Antitrombóticos', summary: 'Anticoagulación IV con esquema y monitorización según indicación.',
    doses: [], precautions: 'No intercambiar protocolos de SCA, TEV y procedimientos. Revisar hemorragia, plaquetas y antecedente de HIT.', monitoring: 'aPTT o anti-Xa según protocolo; hemograma y sangrado.', infusionUnit: 'U/kg/h', sourceIds: ['heparina'] },
  { ...contentReview, id: 'enoxaparina', name: 'Enoxaparina', aliases: ['HBPM', 'LMWH', 'clexane'], category: 'Antitrombóticos', summary: 'Separar profilaxis, tratamiento de TEV y esquemas de SCA.',
    doses: [], precautions: 'El esquema depende de indicación, edad y función renal. Revisar sangrado, HIT y procedimientos neuraxiales.', monitoring: 'Hemograma, plaquetas, función renal y sangrado.', renalRuleIds: ['enoxaparina-profilaxis', 'enoxaparina-anticoag'], sourceIds: ['enoxaparina'] },
  { ...contentReview, id: 'apixaban', name: 'Apixabán', aliases: ['eliquis', 'DOAC', 'anticoagulante oral'], category: 'Antitrombóticos', summary: 'Distinguir FA no valvular del tratamiento de TEV.',
    doses: [{ context: 'FA no valvular, adulto según ficha estadounidense', text: '5 mg VO cada 12 h. Reducir a 2,5 mg cada 12 h si cumple al menos 2: edad ≥80, peso ≤60 kg, creatinina ≥1,5 mg/dL.', sourceId: 'apixaban' }],
    precautions: 'Estos criterios no se trasladan al TEV. Revisar interacciones, sangrado, función renal y ficha local; no sustituye AVK en válvula mecánica.', monitoring: 'Hemograma, función renal/hepática y adherencia.', renalRuleIds: ['apixaban-fa', 'apixaban-tev'], sourceIds: ['apixaban', 'af'] },
  { ...contentReview, id: 'aspirina', name: 'Aspirina', aliases: ['AAS', 'ASA', 'acido acetilsalicilico'], category: 'Antitrombóticos', summary: 'Antiagregación en SCA.',
    doses: [{ context: 'SCA adulto', text: 'Carga VO 162–325 mg, masticada si posible; mantenimiento 75–100 mg/día.', sourceId: 'acs' }],
    precautions: 'Revisar alergia y sangrado.', monitoring: 'Sangrado y tolerancia.', sourceIds: ['acs'] },
  { ...contentReview, id: 'ticagrelor', name: 'Ticagrelor', aliases: ['P2Y12', 'brilinta'], category: 'Antitrombóticos', summary: 'Antiagregante P2Y12 en SCA seleccionado.',
    doses: [{ context: 'SCA sin fibrinolítico', text: 'Carga 180 mg VO; mantenimiento 90 mg cada 12 h.', sourceId: 'acs' }],
    precautions: 'Revisar sangrado y estrategia invasiva.', monitoring: 'Sangrado y tolerancia.', sourceIds: ['acs'] },
  { ...contentReview, id: 'clopidogrel', name: 'Clopidogrel', aliases: ['P2Y12', 'plavix'], category: 'Antitrombóticos', summary: 'P2Y12 según reperfusión y riesgo.',
    doses: [], precautions: 'Carga según estrategia y edad; no intercambiar esquemas con y sin fibrinólisis.', monitoring: 'Sangrado.', sourceIds: ['acs'] },
  { ...contentReview, reviewedAt: '2026-09-15', id: 'prasugrel', name: 'Prasugrel', aliases: ['P2Y12', 'efient'], category: 'Antitrombóticos', summary: 'P2Y12 para SCA tratado con PCI; revisar edad, peso y ACV/AIT.',
    doses: [], precautions: 'No usar con ACV/AIT previo, sangrado activo o insuficiencia hepática grave. Abrí la comparación contextual para revisar la elegibilidad.', monitoring: 'Sangrado y tolerancia.', sourceIds: ['prasugrel', 'acs'] },
  { ...contentReview, reviewedAt: '2026-09-15', id: 'atorvastatina', name: 'Atorvastatina', aliases: ['estatina', 'lipitor', 'LDL', 'hipolipemiante'], category: 'Prevención secundaria', summary: 'Tratamiento hipolipemiante; revisar tolerancia, hepatopatía e interacciones.',
    doses: [], precautions: 'Revisar falla hepática aguda/cirrosis descompensada, síntomas musculares, embarazo y lactancia. Abrí la ficha contextual para orientar la intensidad.', monitoring: 'Perfil lipídico y transaminasas; CK si hay síntomas musculares.', sourceIds: ['atorvastatin', 'lipidMonitoring', 'acs'] },
  { ...contentReview, id: 'magnesio', name: 'Sulfato de magnesio', aliases: ['Mg', 'torsades', 'magnesio'], category: 'Electrolitos', summary: 'Considerar en recurrencia de TV polimórfica asociada a QT largo.',
    doses: [], precautions: 'No es antiarrítmico rutinario para todo paro o TV polimórfica con QT normal.', monitoring: 'ECG y evaluación de causas reversibles.', sourceIds: ['als'] },
  { ...contentReview, id: 'calcio', name: 'Calcio IV', aliases: ['gluconato de calcio', 'cloruro de calcio', 'hiperpotasemia'], category: 'Electrolitos', summary: 'Protección cardíaca en hiperpotasemia con cambios de ECG.',
    doses: [{ context: 'UKKA, cambios ECG por hiperK', text: 'Gluconato 10%: 30 mL en 10 min, o cloruro 10%: 10 mL en 5 min. Confirmar sal y concentración; no son volúmenes equivalentes.', sourceId: 'hyperk' }],
    precautions: 'Cloruro preferido en reanimación/periparo; gluconato en otros contextos.', monitoring: 'ECG y sitio de acceso.', sourceIds: ['hyperk'] },
  { ...contentReview, id: 'insulina', name: 'Insulina regular + glucosa', aliases: ['insulina corriente', 'hiperkalemia', 'polarizante'], category: 'Electrolitos', summary: 'Redistribución de K en hiperpotasemia moderada/grave.',
    doses: [], precautions: 'Aplicar protocolo de insulina/glucosa y prevención de hipoglucemia. La calculadora no elige este esquema.', monitoring: 'Glucemia seriada hasta 6 h y potasio por posible rebote.', infusionUnit: 'U/h', sourceIds: ['hyperk'] },
  { ...contentReview, id: 'dapagliflozina', name: 'Dapagliflozina', aliases: ['iSGLT2', 'forxiga'], category: 'Insuficiencia cardíaca', summary: 'iSGLT2 en tratamiento de IC según fenotipo y estabilidad.',
    doses: [], precautions: 'Revisar ficha local, función renal y situación aguda antes de iniciar o continuar.', monitoring: 'Estado de volumen y función renal.', renalRuleIds: ['dapagliflozina'], sourceIds: ['hfUpdate'] },
  { ...contentReview, id: 'empagliflozina', name: 'Empagliflozina', aliases: ['iSGLT2', 'jardiance'], category: 'Insuficiencia cardíaca', summary: 'iSGLT2 en tratamiento de IC según fenotipo y estabilidad.',
    doses: [], precautions: 'Revisar ficha local, función renal y situación aguda antes de iniciar o continuar.', monitoring: 'Estado de volumen y función renal.', renalRuleIds: ['empagliflozina'], sourceIds: ['hfUpdate'] },
  { ...contentReview, id: 'colchicina', name: 'Colchicina', aliases: ['pericarditis'], category: 'Pericardio', summary: 'Tratamiento de pericarditis en contextos seleccionados.',
    doses: [], precautions: 'Revisar función renal/hepática e interacciones antes de indicar.', monitoring: 'Tolerancia y toxicidad según contexto.', renalRuleIds: ['colchicina'], sourceIds: ['myoperi'] },
];
