import type { ClinicalPathway } from './types';
import { contentReview } from './sources';

export const pathways: ClinicalPathway[] = [
  { ...contentReview, id: 'sca-cest', name: 'SCA con elevación del ST', aliases: ['SCACEST', 'STEMI', 'IAM', 'infarto', 'dolor toracico'], category: 'Coronarias', urgent: true,
    summary: 'Reperfusión y estrategia antitrombótica.', first: 'Activar la red de reperfusión según ECG y contexto.',
    checks: ['Registrar inicio de síntomas y ECG.', 'Definir angioplastia o fibrinólisis según tiempos y contraindicaciones.', 'Revisar sangrado, antitrombóticos previos y función renal.'],
    avoid: 'La medicación no debe demorar la reperfusión.', drugIds: ['aspirina', 'ticagrelor', 'clopidogrel', 'heparina', 'enoxaparina'], sourceIds: ['acs'] },
  { ...contentReview, id: 'sca-sest', name: 'SCA sin elevación del ST', aliases: ['SCASEST', 'NSTEMI', 'angina inestable', 'troponina'], category: 'Coronarias', urgent: true,
    summary: 'Riesgo isquémico, hemorrágico y estrategia invasiva.', first: 'Identificar inestabilidad, isquemia persistente y necesidad de intervención urgente.',
    checks: ['Interpretar ECG y troponinas seriadas.', 'Individualizar estrategia invasiva y antitrombótica.', 'Revisar anticoagulación previa.'],
    avoid: 'No aplicar automáticamente el mismo pretratamiento P2Y12 a todos los pacientes.', drugIds: ['aspirina', 'ticagrelor', 'clopidogrel', 'heparina', 'enoxaparina'], sourceIds: ['acs'] },
  { ...contentReview, id: 'shock', name: 'Shock cardiogénico', aliases: ['bajo gasto', 'hipoperfusion', 'inotropicos', 'SCAI'], category: 'Hemodinámica', urgent: true,
    summary: 'Reconocer el fenotipo, sostener perfusión y tratar la causa.', first: 'Activar el equipo de shock y valorar necesidad de traslado temprano.',
    checks: ['Integrar examen, lactato, diuresis, ECG y ecocardiografía.', 'Distinguir compromiso izquierdo, derecho o biventricular y reevaluar respuesta.', 'Individualizar soporte farmacológico; escalar si persiste hipoperfusión.'],
    avoid: 'No demorar la evaluación de soporte circulatorio ante deterioro pese al tratamiento.', drugIds: ['noradrenalina', 'dobutamina', 'milrinona', 'adrenalina'], sourceIds: ['shock'] },
  { ...contentReview, id: 'ic-aguda', name: 'IC aguda / edema pulmonar', aliases: ['EAP', 'disnea', 'congestion', 'insuficiencia cardiaca', 'edema agudo pulmonar'], category: 'Insuficiencia cardíaca', urgent: true,
    summary: 'Evaluación de congestión, perfusión y desencadenante.', first: 'Valorar soporte respiratorio y perfusión junto con el tratamiento de la congestión.',
    checks: ['ECG, ecocardiografía, función renal y electrolitos.', 'Individualizar diuresis y vasodilatación según estado hemodinámico.', 'Reevaluar congestión y planificar tratamiento y seguimiento antes del alta.'],
    avoid: 'No usar inotrópicos ni opioides de rutina en ausencia de una indicación específica.', drugIds: ['furosemida', 'nitroglicerina', 'dapagliflozina', 'empagliflozina'], sourceIds: ['hf', 'hfUpdate', 'furosemida', 'nitroglicerina'] },
  { ...contentReview, id: 'fa', name: 'Fibrilación / flutter auricular', aliases: ['FA', 'aleteo', 'RVR', 'respuesta ventricular rapida'], category: 'Arritmias', urgent: false,
    summary: 'Estabilidad, control de frecuencia/ritmo y prevención embólica.', first: 'Si la arritmia causa inestabilidad, priorizar cardioversión eléctrica.',
    checks: ['Confirmar ritmo, preexcitación y función ventricular.', 'Revisar duración del episodio y anticoagulación antes de cardioversión programada.', 'Individualizar control de frecuencia y riesgo tromboembólico.'],
    avoid: 'FA preexcitada: evitar bloqueadores nodales y amiodarona IV.', drugIds: ['amiodarona', 'metoprolol', 'esmolol', 'diltiazem', 'digoxina', 'apixaban'], sourceIds: ['af', 'als'] },
  { ...contentReview, id: 'tsv', name: 'Taquicardia regular de QRS estrecho', aliases: ['TSV', 'TPSV', 'supraventricular', 'reentrada'], category: 'Arritmias', urgent: true,
    summary: 'Estabilidad y regularidad antes de elegir el tratamiento.', first: 'Con inestabilidad atribuible al ritmo, cardioversión sincronizada.',
    checks: ['Monitor, acceso IV y ECG.', 'Si estable y regular: maniobras vagales; considerar adenosina.'],
    avoid: 'No extrapolar este circuito a taquicardia irregular o polimórfica.', drugIds: ['adenosina'], sourceIds: ['tachy'] },
  { ...contentReview, id: 'tv', name: 'Taquicardia ventricular / QRS ancho', aliases: ['TV', 'torsades', 'tormenta electrica', 'taquicardia ancha'], category: 'Arritmias', urgent: true,
    summary: 'Separar ausencia de pulso, TV monomórfica y polimórfica.', first: 'Sin pulso: circuito de paro. Con pulso e inestabilidad: terapia eléctrica inmediata.',
    checks: ['Evaluar regularidad, QT y causas reversibles.', 'TV polimórfica: descarga no sincronizada; evaluar QT largo.'],
    avoid: 'No administrar verapamilo/diltiazem a una taquicardia de QRS ancho no aclarada.', drugIds: ['amiodarona', 'lidocaina', 'magnesio'], sourceIds: ['tachy', 'als'] },
  { ...contentReview, id: 'bradicardia', name: 'Bradicardia / bloqueo AV', aliases: ['BAV', 'bloqueo completo', 'atropina', 'marcapasos'], category: 'Arritmias', urgent: true,
    summary: 'Tratar la bradicardia que compromete la perfusión.', first: 'Evaluar hipotensión, alteración del sensorio, isquemia y shock.',
    checks: ['Buscar fármacos, isquemia, hipoxia y alteraciones electrolíticas.', 'Atropina si corresponde; si ineficaz, estimulación y/o infusión cronotrópica.', 'Preparar estimulación transvenosa cuando esté indicada.'],
    avoid: 'No demorar la estimulación en bloqueo avanzado inestable.', drugIds: ['atropina', 'adrenalina', 'dopamina'], sourceIds: ['brady'] },
  { ...contentReview, id: 'paro', name: 'Paro cardiorrespiratorio', aliases: ['PCR', 'RCP', 'ACLS', 'FV', 'asistolia', 'AESP'], category: 'Reanimación', urgent: true,
    summary: 'RCP de calidad y desfibrilación cuando corresponda.', first: 'Activar reanimación, iniciar compresiones y conectar desfibrilador.',
    checks: ['Distinguir FV/TV sin pulso de asistolia/AESP.', 'Minimizar pausas y reevaluar el ritmo por ciclos.', 'Tratar causas reversibles y pasar a cuidados posparo si recupera circulación.'],
    avoid: 'Las drogas no deben retrasar compresiones o descarga indicada.', drugIds: ['adrenalina', 'amiodarona', 'lidocaina'], sourceIds: ['arrest'] },
  { ...contentReview, id: 'tep', name: 'Tromboembolismo pulmonar', aliases: ['TEP', 'EP', 'embolia pulmonar', 'ventriculo derecho'], category: 'Vascular', urgent: true,
    summary: 'Probabilidad diagnóstica, gravedad y riesgo de deterioro.', first: 'Identificar compromiso cardiopulmonar y activar un equipo multidisciplinario en pacientes graves.',
    checks: ['Integrar probabilidad clínica, dímero D cuando corresponda e imagen.', 'Valorar función del VD, biomarcadores y estabilidad.', 'Individualizar anticoagulación, reperfusión y soporte.'],
    avoid: 'La guía 2026 distingue categorías A–E; una ficha breve no reemplaza esa estratificación.', drugIds: ['heparina', 'enoxaparina', 'apixaban'], sourceIds: ['pe'] },
  { ...contentReview, id: 'aorta', name: 'Síndrome aórtico agudo', aliases: ['diseccion aortica', 'hematoma intramural', 'aorta'], category: 'Vascular', urgent: true,
    summary: 'Control del impulso y resolución anatómica urgente.', first: 'Contactar al equipo aórtico/cirugía y definir anatomía y malperfusión.',
    checks: ['Si tolerado: TAS <120 mmHg o la mínima que preserve perfusión; FC 60–80 lpm.', 'Betabloqueo IV inicial si no está contraindicado; luego vasodilatador si precisa.', 'Tipo A: evaluación quirúrgica inmediata.'],
    avoid: 'No bajar presión a expensas de perfusión orgánica.', drugIds: ['esmolol'], sourceIds: ['aorta'] },
  { ...contentReview, id: 'taponamiento', name: 'Taponamiento cardíaco', aliases: ['derrame pericardico', 'shock obstructivo', 'pericardiocentesis'], category: 'Pericardio y miocardio', urgent: true,
    summary: 'Diagnóstico hemodinámico y drenaje.', first: 'Ecocardiografía urgente y coordinación de drenaje en paciente inestable.',
    checks: ['Identificar causa, anatomía y vía de drenaje.', 'Vigilar perfusión mientras se prepara la intervención.'],
    avoid: 'Evitar nitroglicerina: el gasto depende del retorno venoso.', drugIds: [], sourceIds: ['myoperi', 'nitroglicerina'] },
  { ...contentReview, id: 'miopericarditis', name: 'Miocarditis / pericarditis', aliases: ['miopericarditis', 'dolor pericardico', 'miocarditis fulminante'], category: 'Pericardio y miocardio', urgent: false,
    summary: 'Distinguir inflamación pericárdica de compromiso miocárdico.', first: 'Buscar disfunción ventricular, arritmias y compromiso hemodinámico.',
    checks: ['ECG, biomarcadores y ecocardiografía; considerar resonancia.', 'Shock o arritmias graves requieren manejo especializado.', 'Individualizar tratamiento según etiología y fenotipo.'],
    avoid: 'No asumir que todos los cuadros inflamatorios reciben el mismo tratamiento.', drugIds: ['colchicina'], sourceIds: ['myoperi'] },
  { ...contentReview, id: 'endocarditis', name: 'Endocarditis / valvulopatía aguda', aliases: ['infeccion valvular', 'protesis', 'insuficiencia mitral aguda', 'vegetacion'], category: 'Válvulas e infección', urgent: true,
    summary: 'Microbiología, imagen y detección de indicación quirúrgica.', first: 'Activar equipo de endocarditis ante insuficiencia cardíaca o complicaciones.',
    checks: ['Obtener hemocultivos y ecocardiografía según situación clínica.', 'Valorar ETE, prótesis y complicaciones perivalvulares.', 'Individualizar antibióticos y cirugía con infectología y equipo valvular.'],
    avoid: 'Edema refractario o shock por disfunción valvular exige evaluación quirúrgica de emergencia.', drugIds: [], sourceIds: ['endocarditis'] },
  { ...contentReview, id: 'hiperpotasemia', name: 'Hiperpotasemia', aliases: ['hiperkalemia', 'hiperK', 'potasio alto', 'K'], category: 'Metabólico', urgent: true,
    summary: 'Protección cardíaca, redistribución y eliminación de potasio.', first: 'Evaluar ECG y gravedad; monitorizar durante el tratamiento.',
    checks: ['Calcio IV si hay cambios electrocardiográficos.', 'Insulina/glucosa según gravedad, con controles de glucemia hasta 6 h.', 'Planificar eliminación de K y controlar rebote; diálisis urgente cuando corresponde.'],
    avoid: 'El calcio protege el corazón, pero no reduce el potasio.', drugIds: ['calcio', 'insulina'], sourceIds: ['hyperk'] },
  { ...contentReview, id: 'hipertension', name: 'Presión arterial muy elevada', aliases: ['emergencia hipertensiva', 'crisis hipertensiva', 'HTA', 'hipertension'], category: 'Hemodinámica', urgent: false,
    summary: 'Diferenciar lesión aguda de órgano blanco de elevación asintomática.', first: 'Repetir una medición correcta y buscar daño orgánico agudo.',
    checks: ['Evaluar clínica neurológica, cardíaca, renal y aórtica.', 'Elegir objetivo y tratamiento según el órgano afectado.', 'Reevaluar respuesta y evitar descensos excesivos.'],
    avoid: 'Una cifra aislada, sin lesión aguda, no justifica automáticamente antihipertensivos IV.', drugIds: ['nitroglicerina', 'esmolol'], sourceIds: ['hypertension', 'aorta', 'nitroglicerina'] },
];
