import type { ClinicalSource } from './types';

export const contentReview = { reviewedAt: '2026-09-14', validation: 'pending-local-review' as const };
export const clinicalSources: Record<string, ClinicalSource> = {
  acsAntithrombotics: { title: 'ACC/AHA · Recomendaciones antitrombóticas en SCA', year: '2025', url: 'https://www.jacc.org/doi/10.1016/j.jacc.2025.04.002' },
  acsDischarge: { title: 'ACC/AHA · Prevención secundaria y seguimiento tras SCA', year: '2025', url: 'https://www.acc.org/About-ACC/Press-Releases/2025/02/28/17/51/ACC-AHA-Issue-New-Acute-Coronary-Syndromes-Guideline' },
  arcHbr: { title: 'ESC · Riesgo hemorrágico y personalización de DAPT', year: '2023', url: 'https://www.escardio.org/communities/councils/cardiology-practice/education/cardiopractice/dual-antiplatelet-therapy-for-the-general-cardiologist-recent-evidence-balanci/' },
  ticagrelor: { title: 'AEMPS · Brilique 90 mg, ficha técnica', year: 'Consulta 2026', url: 'https://cima.aemps.es/cima/dochtml/ft/10655006/FT_10655006.html' },
  prasugrel: { title: 'AEMPS · Prasugrel, ficha técnica', year: 'Consulta 2026', url: 'https://cima.aemps.es/cima/dochtml/ft/83508/FT_83508.html' },
  clopidogrel: { title: 'AEMPS · Clopidogrel, ficha técnica', year: 'Consulta 2026', url: 'https://cima.aemps.es/cima/dochtml/ft/71372/FT_71372.html' },
  atorvastatin: { title: 'DailyMed · Atorvastatina, ficha de prescripción', year: 'Consulta 2026', url: 'https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=a60cc18b-0631-4cf0-b021-9f52224ece65' },
  lipidMonitoring: { title: 'NICE NG238 · Estatinas y monitorización', year: '2023', url: 'https://www.nice.org.uk/guidance/ng238/chapter/recommendations' },
  hf2022: { title: 'AHA/ACC/HFSA · Guía de insuficiencia cardíaca', year: '2022', url: 'https://www.heart.org/-/media/832EA0F4E73948848612F228F7FA2D35.pdf' },
  hfMonitoring: { title: 'NICE NG106 · Tratamiento y seguimiento de IC', year: 'Actualización 2025', url: 'https://www.nice.org.uk/guidance/ng106/chapter/recommendations' },
  kdigo: { title: 'KDIGO · Evaluación y manejo de enfermedad renal crónica', year: '2024', url: 'https://kdigo.org/wp-content/uploads/2024/03/KDIGO-2024-CKD-Guideline.pdf' },
  diabetesHospital: { title: 'ADA · Diabetes en el hospital y transición al alta', year: '2026', url: 'https://diabetesjournals.org/care/article/49/Supplement_1/S339/163925/16-Diabetes-Care-in-the-Hospital-Standards-of-Care' },
  liverTests: { title: 'BSG · Evaluación de análisis hepáticos anormales', year: '2018', url: 'https://www.bsg.org.uk/clinical-resource/guidelines-on-abnormal-liver-blood-tests' },
  platelets: { title: 'NHS Highland · Evaluación y derivación por trombocitopenia', year: 'Consulta 2026', url: 'https://www.rightdecisions.scot.nhs.uk/tam-treatments-and-medicines-nhs-highland/therapeutic-guidelines/haematology/thrombocytopenia-guidelines/' },
  arrest: { title: 'AHA · Algoritmo de paro cardíaco adulto', year: '2025', url: 'https://cpr.heart.org/-/media/CPR-Files/CPR-Guidelines-Files/2025-Algorithms/Algorithm-ACLS-CA-250527.pdf?sc_lang=en' },
  tachy: { title: 'AHA · Taquiarritmia con pulso', year: '2025', url: 'https://cpr.heart.org/-/media/CPR-Files/CPR-Guidelines-Files/2025-Algorithms/Algorithm-ACLS-Tachycardia-250514.pdf?sc_lang=en' },
  brady: { title: 'AHA · Bradicardia con pulso', year: '2025', url: 'https://cpr.heart.org/-/media/CPR-Files/CPR-Guidelines-Files/2025-Algorithms/Algorithm-ACLS-Bradycardia-250514.pdf?sc_lang=en' },
  als: { title: 'AHA · Soporte vital avanzado en adultos', year: '2025', url: 'https://cpr.heart.org/en/resuscitation-science/cpr-and-ecc-guidelines/adult-advanced-life-support' },
  acs: { title: 'ACC/AHA · Guía de síndrome coronario agudo', year: '2025', url: 'https://www.jacc.org/doi/10.1016/j.jacc.2024.11.009' },
  shock: { title: 'ACC · Orientación clínica en shock cardiogénico', year: '2025', url: 'https://www.acc.org/About-ACC/Press-Releases/2025/03/18/19/19/American-College-of-Cardiology-Issues-Concise-Clinical-Guidance-on-Evaluation-and-Management-of-Cardiogenic-Shock' },
  hf: { title: 'ESC · Insuficiencia cardíaca, puntos clave publicados por ACC', year: '2021', url: 'https://www.acc.org/Latest-in-Cardiology/ten-points-to-remember/2021/08/29/18/05/2021-ESC-Guidelines-for-HF-ESC-2021' },
  hfUpdate: { title: 'ESC · Actualización de insuficiencia cardíaca, resumen ACC', year: '2023', url: 'https://www.acc.org/latest-in-cardiology/ten-points-to-remember/2023/08/29/14/58/2023-focused-update-esc-guidelines-hf-esc-2023' },
  af: { title: 'ESC · Fibrilación auricular, puntos clave publicados por ACC', year: '2024', url: 'https://www.acc.org/Latest-in-Cardiology/ten-points-to-remember/2024/09/17/04/05/2024-ESC-guidelines-for-AF-esc-2024' },
  pe: { title: 'ACC/AHA · Nueva guía de embolia pulmonar aguda', year: '2026', url: 'https://www.acc.org/About-ACC/Press-Releases/2026/02/19/19/27/First-AHAACC-acute-pulmonary-embolism-guideline-prompt-diagnosis-and-treatment-are-key' },
  aorta: { title: 'ACC/AHA · Enfermedad aórtica, puntos clave (parte 2)', year: '2022', url: 'https://www.acc.org/latest-in-cardiology/ten-points-to-remember/2022/11/01/12/21/2022-guideline-on-aortic-disease-2-gl-ad' },
  myoperi: { title: 'ESC · Miocarditis y pericarditis, material oficial', year: '2025', url: 'https://www.escardio.org/static-file/Escardio/Guidelines/Products/Slide%20sets/2025/2025%20official%20slides_MyoPeri.pdf' },
  endocarditis: { title: 'ESC · Endocarditis, puntos clave publicados por ACC', year: '2023', url: 'https://www.acc.org/Latest-in-Cardiology/ten-points-to-remember/2023/08/29/20/49/2023-esc-guidelines-for-endocarditis-esc-2023' },
  hyperk: { title: 'UK Kidney Association · Hiperpotasemia en adultos', year: 'Actualización julio 2026', url: 'https://www.ukkidney.org/sites/default/files/documents/FINAL%20VERSION%20-%20UKKA%20CLINICAL%20PRACTICE%20GUIDELINE%20-%20MANAGEMENT%20OF%20HYPERKALAEMIA%20IN%20ADULTS%20-%20UPDATED%20JULY%202026_0.pdf' },
  hypertension: { title: 'AHA · Presión arterial elevada en atención aguda', year: '2024', url: 'https://professional.heart.org/en/science-news/management-of-elevated-blood-pressure-in-the-acute-care-setting' },
  noradrenalina: { title: 'DailyMed · LEVOPHED, ficha de prescripción', year: 'Consulta 2026', url: 'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c4de72a8-2a75-4984-ce90-e4870226dc12' },
  dobutamina: { title: 'DailyMed · Dobutamina, ficha de prescripción', year: 'Consulta 2026', url: 'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=74ba9408-17d3-48ac-be0b-a4fee9e7a1a5' },
  milrinona: { title: 'DailyMed · Milrinona, ficha de prescripción', year: 'Consulta 2026', url: 'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0fdaee3c-2144-4ca7-9868-54d251f468c0' },
  vasopresina: { title: 'DailyMed · VASOSTRICT, ficha de prescripción', year: 'Consulta 2026', url: 'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b1147beb-743e-4c62-8927-91192447f8b8' },
  levosimendan: { title: 'AEMPS · Simdax, ficha técnica', year: 'Consulta 2026', url: 'https://cima.aemps.es/cima/dochtml/ft/64154/FichaTecnica_64154.html' },
  nitroglicerina: { title: 'DailyMed · Nitroglicerina IV, ficha de prescripción', year: 'Consulta 2026', url: 'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=578d8159-5ec6-457f-b4a8-9add624d43a8' },
  furosemida: { title: 'DailyMed · Furosemida IV, ficha de prescripción', year: 'Consulta 2026', url: 'https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=ddfc41a9-37d4-49c1-bbf3-969a98cd649c&version=7' },
  heparina: { title: 'DailyMed · Heparina sódica, ficha de prescripción', year: 'Consulta 2026', url: 'https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=ad0f410c-6121-43f9-9844-943472961cb0' },
  enoxaparina: { title: 'DailyMed · Enoxaparina, ficha de prescripción', year: 'Consulta 2026', url: 'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=066f27ec-352c-4051-ba29-248e292690db' },
  apixaban: { title: 'DailyMed · ELIQUIS, ficha de prescripción', year: 'Consulta 2026', url: 'https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=a454cd24-0c6d-46e8-b1e4-197388606175&version=38' },
};
